public class claseTipoDeDatos {
    
    //private final X = 1;
    private integer i = 5;
    private double d = 4.2;
    private String hello = 'Hello World!';
    private boolean verdad = true;
    private DateTime myDateTime = DateTime.now();
    
    
    public void imprimir(){
        //System.Debug(X);
        System.Debug(i);
        System.Debug(d);
        System.Debug(hello);
        System.Debug(verdad);
        System.Debug(myDateTime);
    }
}